# Promise.prototype.finally()（Promise 是如何"兜底"操作的）

"兜底"操作指不管最后状态如何都会执行的回调函数。

Promise.prototype.finally() 方法返回一个 Promise，在 promise 执行结束时，无论结果是 fulfilled 或者是 rejected，在执行 then()和 catch()后，都会执行 finally 指定的回调函数。这为指定执行完 promise 后，无论结果是 fulfilled 还是 rejected 都需要执行的代码提供了一种方式，避免同样的语句需要在 then()和 catch()中各写一次的情况。

```js
p.finally(onFinally);

p.finally(function () {
  // 返回状态为(resolved 或 rejected)
});
```

```js
new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success');
    // reject('fail')
  }, 1000);
})
  .then((res) => {
    console.log(res);
  })
  .catch((err) => {
    console.log(err);
  })
  .finally(() => {
    console.log('finally');
  });
```

## 场景 1：loading 关闭

需要每次发送请求，都会有 loading 提示，请求发送完毕，就需要关闭 loading 提示框，不然界面就无法被点击。不管请求成功或是失败，这个 loading 都需要关闭掉，这时把关闭 loading 的代码写在 finally 里再合适不过了。

## 场景 2：数据库断开链接

```js
let connection
db.open()
    .then(conn => {
        connection = conn
        return connection.select({
            name: 'Jane'
        })
    })
    .then(result => {
        // Process result
        // Use `connection` to make more queries
    })···
    .catch(error => {
        // handle errors
    })
    .finally(() => {
        connection.close()
    })
```

## Promise 生成器

```js
// Promise 生成器
function Gen(time) {
  return new Promise((resolve, reject) => {
    setTimeout(function () {
      if (time < 500) {
        reject(time);
      } else {
        resolve(time);
      }
    }, time);
  });
}

// 异步调用函数 无论成功还是失败都会执行 finally 的内容
Gen(Math.random() * 1000)
  .then((val) => console.log('resolve', val))
  .catch((err) => console.log('reject', err))
  .finally(() => {
    console.log('finish');
  });
```

## 链接

- [Promise.prototype.finally()](http://2ality.com/2017/07/promise-prototype-finally.html)
- [MDN Promise.prototype.finally()](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally)
