# Promise.allSettled()

学习了 ES 新特性，都知道 Promise.all() 具有并发执行异步任务的能力。但它的最大问题就是如果其中某个任务出现异常(reject)，所有任务都会挂掉，Promise 直接进入 reject 状态。

`Promise.allSettled()`方法返回一个在所有给定的 promise 已被决议或被拒绝后决议的 promise，并带有一个对象数组，每个对象表示对应的 promise 结果。

场景：现在页面上有三个请求，分别请求不同的数据，如果一个接口服务异常，整个都是失败的，都无法渲染出数据

```js
Promise.all([
  Promise.reject({
    code: 500,
    msg: '服务异常',
  }),
  Promise.resolve({
    code: 200,
    data: ['1', '2', '3'],
  }),
  Promise.resolve({
    code: 200,
    data: ['4', '5', '6'],
  }),
])
  .then((res) => {
    console.log(res);
    console.log('成功');
  })
  .catch((err) => {
    console.log(err);
    console.log('失败');
  });
```

需要一种机制，如果并发任务中，无论一个任务正常或者异常，都会返回对应的的状态

```js
Promise.allSettled([
  Promise.reject({
    code: 500,
    msg: '服务异常',
  }),
  Promise.resolve({
    code: 200,
    data: ['1', '2', '3'],
  }),
  Promise.resolve({
    code: 200,
    data: ['4', '5', '6'],
  }),
])
  .then((res) => {
    console.log('成功');
    console.log(res);
    const data = res.filter((item) => item.status === 'fulfilled');
    console.log(data);
  })
  .catch((err) => {
    console.log(err);
    console.log('失败');
  });
```

Promise.allSettled：一个新的 Promise 组合器，不像all、race一样具有短路特性

## 链接

- [Promise.allSettled()](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled)
- [npm promise.allsettled](https://www.npmjs.com/package/promise.allsettled)
- [promise-all-settled](https://www.npmjs.com/package/promise-all-settled)
- [promise-settle](https://www.npmjs.com/package/promise-settle)
